# Generated by Django 5.2.16 on 2026-07-15 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Activo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("DOMINIO", "Dominio"), ("HOSTING", "Hosting")],
                        max_length=10,
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("empresa", models.CharField(max_length=255)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("HABILITADO", "Habilitado"),
                            ("DESHABILITADO", "Deshabilitado"),
                        ],
                        default="HABILITADO",
                        max_length=15,
                    ),
                ),
                ("encargado", models.CharField(max_length=255)),
                ("empresa_responsable", models.CharField(max_length=255)),
                (
                    "estado_pago",
                    models.CharField(
                        choices=[("PAGADO", "Pagado"), ("PENDIENTE", "Pendiente")],
                        default="PENDIENTE",
                        max_length=10,
                    ),
                ),
                ("vencimiento", models.DateField()),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("actualizado", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["vencimiento"],
            },
        ),
    ]
