# Generated by Django 5.2.16 on 2026-07-16 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activo",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("DOMINIO", "Dominio"),
                    ("HOSTING", "Hosting"),
                    ("LICENCIA", "Licencia"),
                ],
                max_length=10,
            ),
        ),
    ]
